import {
  Fira_Sans,
  Inter,
  Montserrat,
  Noto_Sans,
  Nunito_Sans,
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar.js";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
